name: CI/CD Pipeline

# Run this workflow on every push or pull request to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Wait for the setup
        run: sleep 10

      # Step 3: Install dependencies
      - name: Install NPM
        run: npm install
      - name: Wait for the setup
        run: sleep 10
      - name: Install Jest & Supertest
        run: npm install jest supertest 
      - name: Wait for the setup
        run: sleep 10

      # Step 4: Run tests 
      - name: Run tests
        run: npx jest specs/poc.specs.ts

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # Step 5: Deploy 
      - name: Deploy
        run: echo "Deploying to the server..."
